name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. 3.0.0-beta0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Check Bun version
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Zip extensions
        run: |
          bun run zip
          bun run zip:firefox

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          prerelease: ${{ contains(env.TAG_NAME, 'beta') }}
          files: |
            .output/stape-gtm-helper-${{ env.TAG_NAME }}-chrome.zip
            .output/stape-gtm-helper-${{ env.TAG_NAME }}-firefox.zip
            .output/stape-gtm-helper-${{ env.TAG_NAME }}-firefox-sources.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
